name: 🚀 Build and deploy JupyterLite site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar JupyterLite
        run: pip install jupyterlite[all]
      - name: Construir el sitio JupyterLite
        run: jupyter lite build --output-dir _output
      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_output
